.TH stash 1 "2023-10-24" "Version 2.0.0"

.SH NAME

stash - simple POSIX symlink manager.

.SH SYNOPSIS

.B stash \fR[-\fBdfuVq\fR]
.I source target \fR

.B stash \fR-\fBh

.B stash \fR-\fBV


.SH DESCRIPTION

.B stash
symlinks the entire contents of a
.I source
directory to some
.I target
directory.

The subdirectory structure of the
.I source
is copied to the
.I target
directory.
This makes
.B stash
suited to linking user configuration files stored in version controlled
repositories to directories that might also be populated by application data.

.SH OPTIONS

.TP
.B -h|--help
Display a brief usage message.

.TP
.B -V|--version
Print version.

.TP
.B -q|--quiet
Quiet mode. Suppress messags.

.TP
.B -d|--dry-run
Dry-run mode. When set, the filesystem is not modified.

.TP
.B -f|--force
Force the removal of target files  before linking.

.TP
.B -u|--unlink|--rm
Remove (unlink) links in target links rather than create them. When
.B -f
is set, remove target files (even non-links). Subdirs in the target are
removed only if they are empty.


.SH EXAMPLES

.HP
.B stash \fI config ~/.config

Link the files in the
.I config
dir to the default XDG_CONFIG_HOME location.

.HP
.B stash -dv \fI config ~/.config

Execute a dry-run to see a plan of what will
be linked from the
.I config
dir to the default XDG_CONFIG_HOME location.


.SH SEE ALSO

.TP
.B stow
A more feature rich symlink manager written in perl
(https://www.gnu.org/software/stow/).

.TP
.B stowsh
A bash port of
.B stow
that seeks more feature parity than
.B stash
(https://github.com/williamsmj/stowsh).
